-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["tube_l2b"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   8.08240699768066, 1.81755924224854  ,  9.93520545959473, -1.1944465637207  ,  11.8980159759521, 15.9033994376659  ,  8.32527351379395, 15.8966942206025  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.456650197506, -11.0626831054688  ,  -2.32956409454346, -11.0264301300049  ,  -4.53305816650391, -7.83283615112305  ,  -15.6699669957161, -7.9294376373291  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -2.32956409454346, -11.0264301300049  ,  5.36690902709961, -6.84944343566895  ,  1.38173866271973, -6.11221122741699  ,  -4.53305816650391, -7.83283615112305  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   5.36690902709961, -6.84944343566895  ,  5.42055130004883, -3.84016609191895  ,  1.38173866271973, -6.11221122741699  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   9.93520545959473, -1.1944465637207  ,  8.08240699768066, 1.81755924224854  ,  5.42055130004883, -3.84016609191895  ,  5.36690902709961, -6.84944343566895  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -10.6094608306885, 15.7799780070782  ,  -11.0882592201233, 10.106342792511  ,  -10.1694169044495, 8.29923009872437  ,  -8.84928512573242, 10.0594058036804  ,  -7.41914176940918, 12.2596259117126  ,  -7.41914176940918, 15.6699669957161  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.5599560141563, 7.52915287017822  ,  -10.1694169044495, 8.29923009872437  ,  -11.0882592201233, 10.106342792511  ,  -15.6699669957161, 9.72937297821045  }
				}  
		}
		
		, 
		["tube_l2t"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.63916397094727, -13.1529140472412  ,  -9.06930685043335, -10.1826171875  ,  -11.4895491600037, -8.75247573852539  ,  -11.4895491600037, -12.3388347625732  ,  -10.1694169044495, -15.903190612793  ,  -7.57315635681152, -15.8591861724854  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.7799780070782, -8.97249603271484  ,  -15.6699669957161, -12.4928493499756  ,  -11.4895491600037, -12.3388347625732  ,  -11.4895491600037, -8.75247573852539  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   10.2926292419434, -15.7931785583496  ,  9.19251823425293, 1.14851474761963  ,  7.76237678527832, -4.46204566955566  ,  7.76237678527832, -15.6831684112549  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -2.02860355377197, 7.41914176940918  ,  0.391639709472656, 9.61936187744141  ,  -16, 11.2695269584656  ,  -16, 8.23322296142578  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   3.14191436767578, 4.99890041351318  ,  0.391639709472656, 9.61936187744141  ,  -2.02860355377197, 7.41914176940918  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   3.14191436767578, 4.99890041351318  ,  5.6281623840332, 2.07260704040527  ,  9.19251823425293, 1.14851474761963  ,  0.391639709472656, 9.61936187744141  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   7.76237678527832, -4.46204566955566  ,  9.19251823425293, 1.14851474761963  ,  5.6281623840332, 2.07260704040527  }
				}  
		}
		
		, 
		["tube_r2b"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   7.87041854858398, -7.87041854858398  ,  6.33589172363281, -9.91645431518555  ,  15.798807144165, -10.0017051696777  ,  15.9863586425781, -7.54646110534668  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -1.08098793029785, -7.1031551361084  ,  -2.70076656341553, -9.42199516296387  ,  6.33589172363281, -9.91645431518555  ,  7.87041854858398, -7.87041854858398  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -4.2352933883667, -3.77834701538086  ,  -7.13384437561035, -5.73913192749023  ,  -2.70076656341553, -9.42199516296387  ,  -1.08098793029785, -7.1031551361084  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.13384437561035, 0.995737075805664  ,  -10.5439043045044, -0.538789749145508  ,  -7.13384437561035, -5.73913192749023  ,  -4.2352933883667, -3.77834701538086  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.13384437561035, 0.995737075805664  ,  -7.56010150909424, 16  ,  -10.6291556358337, 16  ,  -10.5439043045044, -0.538789749145508  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   8.12617301940918, 15.9147485047579  ,  8.04092216491699, 11.1406645774841  ,  9.06394004821777, 8.99232864379883  ,  10.6837177276611, 13.016197681427  ,  10.8542213439941, 15.9147485047579  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   9.06394004821777, 8.99232864379883  ,  11.6214847564697, 8.15686225891113  ,  15.969310760498, 7.98635959625244  ,  15.9863586425781, 10.100597858429  ,  10.6837177276611, 13.016197681427  }
				}  
		}
		
		, 
		["tube_r2t"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   15.9345207214355, 11.9911541938782  ,  -2.68764495849609, 8.7294921875  ,  15.9525756835938, 8.17588567733765  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.60017395019531, -5.03827095031738  ,  -7.75262260437012, 4.36255550384521  ,  -11.0584077835083, -15.802734375  ,  -8.14518356323242, -15.802734375  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -2.68764495849609, 8.7294921875  ,  1.54489707946777, 7.43266582489014  ,  8.92073631286621, 8.23304319381714  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -2.68764495849609, 8.7294921875  ,  -7.75262260437012, 4.36255550384521  ,  -3.54817390441895, 4.60228061676025  ,  1.54489707946777, 7.43266582489014  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.75262260437012, 4.36255550384521  ,  -6.29330730438232, 0.746852874755859  ,  -3.54817390441895, 4.60228061676025  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 1, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.75262260437012, 4.36255550384521  ,  -7.60017395019531, -5.03827095031738  ,  -6.29330730438232, 0.746852874755859  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   13.5822696685791, -7.7851676940918  ,  9.14346504211426, -8.38421630859375  ,  7.87041854858398, -11.1099758148193  ,  10.8542213439941, -11.1952266693115  ,  15.969310760498, -10.5984668731689  ,  15.8723430633545, -8.00710105895996  }
				}  ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   7.87041854858398, -11.1099758148193  ,  7.87041854858398, -15.8840599060059  ,  10.4279632568359, -15.8840599060059  ,  10.8542213439941, -11.1952266693115  }
				}  
		}
		
		, 
		["tube_vertical"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -7.74715137481689, -16.0454559326172  ,  -7.76781368255615, 15.793388441205  ,  -9.73062324523926, 15.793388441205  ,  -9.83392906188965, -16.0454559326172  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   9.90838623046875, 16.1167162135243  ,  7.73896408081055, 16.1167162135243  ,  7.73896408081055, -15.7221279144287  ,  9.92904853820801, -16.0320434570312  }
				}  
		}
		
		, 
		["tube_horizontal"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.8693271875381, -7.89863967895508  ,  -15.9932953855023, -9.88211059570312  ,  16.1554641723633, -9.88211059570312  ,  16.0521583557129, -7.89863967895508  }
				}   ,
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.9033994376659, 7.76056098937988  ,  15.728832244873, 7.76056098937988  ,  15.7081699371338, 9.95064544677734  ,  -15.9033994376659, 9.95064544677734  }
				}  
		}
		
		, 
		["matraz"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0.7, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -15.9076638966799, 4.07017517089844  ,  16.0590934753418, 4.07017517089844  ,  16.0406265258789, 13.4145891666412  ,  -15.8153277933598, 13.6915974617004  }
				}  
		}
		
		, 
		["antenna"] = {
			
				{
                                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0.5, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   5.99807929992676, 5.52929878234863  ,  -13.2933385372162, 13.4611167907715  ,  12.3381366729736, -12.1460132598877  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


